version: 2.1

jobs:
  test_and_build:
    docker:
      - image: cimg/node:22.14.0
    steps:
      - checkout
      - run:
          name: 'npm install'
          command: 'npm ci'
      - run:
          name: 'lint'
          command: 'npm run lint'
      - run:
          name: 'build'
          command: 'npm run build'

workflows:
  test_and_build:
    jobs:
      - test_and_build
